use_default_settings: true

general:
  instance_name: "MyAI Search"

search:
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  limiter: false
  public_instance: false

engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: wikidata
    engine: wikidata
    shortcut: wd

  - name: startpage
    engine: startpage
    shortcut: sp

  - name: yahoo
    engine: yahoo
    shortcut: yh
